<Project>

  <PropertyGroup>
    <FabInspectorVersionPrefix Condition="'$(FabInspectorVersionPrefix)' == ''">3.5.1</FabInspectorVersionPrefix>
    <VersionPrefix Condition="'$(VersionPrefix)' == ''">$(FabInspectorVersionPrefix)</VersionPrefix>
    <Version Condition="'$(Version)' == ''">$(VersionPrefix)</Version>
    <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">$(VersionPrefix).0</AssemblyVersion>
    <FileVersion Condition="'$(FileVersion)' == ''">$(VersionPrefix).0</FileVersion>
    <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(Version)</InformationalVersion>
  </PropertyGroup>

</Project>